# Generated by Django 4.2.9 on 2024-02-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigIntegerField(db_column='CATEGORY_ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CATEGORY_NAME', max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.BigIntegerField(db_column='COMP_ID', primary_key=True, serialize=False)),
                ('comp_name', models.CharField(db_column='COMP_NAME', max_length=255)),
                ('comp_model', models.CharField(db_column='COMP_MODEL', max_length=255)),
                ('comp_url', models.TextField(db_column='COMP_URL')),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigIntegerField(db_column='POST_ID', primary_key=True, serialize=False)),
                ('category_id', models.BigIntegerField(db_column='CATEGORY_ID')),
                ('post_title', models.CharField(db_column='POST_TITLE', max_length=300)),
                ('post_content', models.TextField(db_column='POST_CONTENT')),
                ('post_created', models.DateTimeField(db_column='POST_CREATED')),
                ('post_clicked', models.IntegerField(blank=True, db_column='POST_CLICKED', null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='testPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(db_column='POST_TITLE', max_length=400)),
            ],
            options={
                'db_table': 'testPost',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='USER_ID', max_length=255)),
                ('user_password', models.CharField(db_column='USER_PASSWORD', max_length=255)),
                ('user_nickname', models.CharField(db_column='USER_NICKNAME', max_length=255)),
                ('user_created', models.DateTimeField(db_column='USER_CREATED')),
                ('user_description', models.CharField(blank=True, db_column='USER_DESCRIPTION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(db_column='SITE_ID', max_length=255, primary_key=True, serialize=False)),
                ('site_url', models.TextField(db_column='SITE_URL')),
                ('comp', models.ForeignKey(blank=True, db_column='COMP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.company')),
                ('post', models.ForeignKey(db_column='POST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.post')),
            ],
            options={
                'db_table': 'site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Postcategory',
            fields=[
                ('mapping_id', models.BigIntegerField(db_column='MAPPING_ID', primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='CATEGORY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.category')),
                ('post', models.ForeignKey(db_column='POST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.post')),
            ],
            options={
                'db_table': 'postcategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.BigIntegerField(db_column='IMAGE_ID', primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='IMAGE_URL')),
                ('post', models.ForeignKey(db_column='POST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.post')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('key', models.CharField(db_column='Key', max_length=255, primary_key=True, serialize=False)),
                ('com_content', models.CharField(db_column='COM_CONTENT', max_length=255)),
                ('com_created', models.DateTimeField(db_column='COM_CREATED')),
                ('com_updated', models.DateTimeField(db_column='COM_UPDATED')),
                ('id', models.ForeignKey(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.user')),
                ('post', models.ForeignKey(db_column='POST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ssanmyApp.post')),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
